spring.application.name=demo

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/db_chic
spring.datasource.username=root
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type=TRACE
Spring.servlet.multipart.location=src/main/resource/static

# Kunci rahasia untuk menandatangani token JWT (harus panjang dan acak)
chicpants.app.jwtSecret=VGhpcyBJcyBBIExvbmcgU2VjcmV0IEtleUZvckNoaWNQYW50c0FwcGxpY2F0aW9uVGhhdE11c3RCZUExMjMyNDU2Nzg5MA==

# Waktu kedaluwarsa token dalam milidetik (contoh: 24 jam)
chicpants.app.jwtExpirationMs=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dedydarmawan876@gmail.com
spring.mail.password=naif ydpf vtwx rvos
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true